name = "aravalipadu02"
compatibility_date = "2024-12-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "arab_db"
database_id = "83b79fc2-7a67-43f5-b632-8b57c5cc72b6"
